# Generated by Django 2.1.5 on 2019-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bioplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genea', models.CharField(blank=True, db_column='GeneA', max_length=255, null=True)),
                ('geneb', models.CharField(blank=True, db_column='GeneB', max_length=255, null=True)),
                ('uniprota', models.CharField(blank=True, db_column='UniprotA', max_length=255, null=True)),
                ('uniprotb', models.CharField(blank=True, db_column='UniprotB', max_length=255, null=True)),
                ('symbola', models.CharField(blank=True, db_column='SymbolA', max_length=255, null=True)),
                ('symbolb', models.CharField(blank=True, db_column='SymbolB', max_length=255, null=True)),
            ],
            options={
                'db_table': 'bioplex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geneontology',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uniprotid', models.CharField(max_length=10)),
                ('ontology', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'geneontology',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1', models.CharField(blank=True, max_length=15, null=True)),
                ('participant2', models.CharField(blank=True, max_length=15, null=True)),
                ('methods', models.PositiveIntegerField()),
                ('papers', models.PositiveIntegerField()),
                ('experiments', models.PositiveIntegerField()),
                ('curationevents', models.PositiveIntegerField()),
                ('intact', models.PositiveIntegerField()),
                ('hprd', models.PositiveIntegerField()),
                ('dip', models.PositiveIntegerField()),
                ('biogrid', models.PositiveIntegerField()),
                ('bioplex', models.PositiveIntegerField()),
                ('pdb', models.IntegerField()),
                ('participant1_uniprot_name', models.CharField(blank=True, max_length=45, null=True)),
                ('participant2_uniprot_name', models.CharField(blank=True, max_length=45, null=True)),
                ('participant1_taxon_id', models.PositiveIntegerField(blank=True, null=True)),
                ('participant2_taxon_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ee', models.IntegerField(blank=True, null=True)),
                ('mi_types', models.IntegerField(blank=True, db_column='MI_types', null=True)),
            ],
            options={
                'db_table': 'interaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interpro',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('uniprotid', models.CharField(max_length=10)),
                ('family', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'interpro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intmetpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.PositiveIntegerField(blank=True, null=True)),
                ('paper', models.IntegerField(blank=True, null=True)),
                ('role1', models.PositiveIntegerField(blank=True, null=True)),
                ('role2', models.PositiveIntegerField(blank=True, null=True)),
                ('multiple', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('sourceid', models.CharField(blank=True, db_column='sourceId', max_length=50, null=True)),
                ('mi_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'intmetpaper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psimi_id', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('pubmed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('journal', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdbinterfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbid', models.CharField(blank=True, db_column='pdbId', max_length=10, null=True)),
                ('interaction', models.IntegerField(blank=True, null=True)),
                ('chain1', models.CharField(blank=True, max_length=15, null=True)),
                ('chain2', models.CharField(blank=True, max_length=15, null=True)),
                ('residues', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('salt', models.IntegerField(blank=True, null=True)),
                ('disulphide', models.IntegerField(blank=True, null=True)),
                ('hydrogen', models.IntegerField(blank=True, null=True)),
                ('nonbonded', models.IntegerField(blank=True, db_column='nonBonded', null=True)),
            ],
            options={
                'db_table': 'pdbinterfaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdbuniprot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbid', models.CharField(blank=True, db_column='pdbID', max_length=10, null=True)),
                ('chain', models.CharField(blank=True, max_length=1, null=True)),
                ('uniprotid', models.CharField(blank=True, db_column='uniprotID', max_length=10, null=True)),
            ],
            options={
                'db_table': 'pdbuniprot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('uniprotid', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'pfam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ppimethods',
            fields=[
                ('psi_mi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_type', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_id', models.IntegerField(blank=True, null=True)),
                ('meta_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ppimethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=30, null=True)),
                ('gene_id', models.CharField(blank=True, max_length=12, null=True)),
                ('uniprot_name', models.CharField(blank=True, max_length=45, null=True)),
                ('uniprot_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('taxon_id', models.PositiveIntegerField(blank=True, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'protein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proteomes',
            fields=[
                ('proteome_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('taxon_id', models.IntegerField(blank=True, null=True)),
                ('proteins', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proteomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProteomesAnterior',
            fields=[
                ('proteome_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('taxon_id', models.IntegerField(blank=True, null=True)),
                ('proteins', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proteomes_anterior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reactome',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('uniprotid', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'reactome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('proteome', models.IntegerField(blank=True, null=True)),
                ('reviewed', models.CharField(blank=True, max_length=20, null=True)),
                ('interactions1', models.IntegerField(blank=True, null=True)),
                ('interactingproteins1', models.IntegerField(blank=True, null=True)),
                ('interactions2', models.IntegerField(blank=True, null=True)),
                ('interactingproteins2', models.IntegerField(blank=True, null=True)),
                ('interactions3', models.IntegerField(blank=True, null=True)),
                ('interactingproteins3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonAntesEe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('proteome', models.IntegerField(blank=True, null=True)),
                ('reviewed', models.CharField(blank=True, max_length=20, null=True)),
                ('interactions1', models.IntegerField(blank=True, null=True)),
                ('interactingproteins1', models.IntegerField(blank=True, null=True)),
                ('interactions2', models.IntegerField(blank=True, null=True)),
                ('interactingproteins2', models.IntegerField(blank=True, null=True)),
                ('interactions3', models.IntegerField(blank=True, null=True)),
                ('interactingproteins3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxon_antes_ee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uniprotid',
            fields=[
                ('current_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('deprecated_id', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'uniprotid',
                'managed': False,
            },
        ),
    ]
