# Generated by Django 2.1.5 on 2019-01-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchProtein', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={},
        ),
    ]
